services:
  app:
    build: .
    image: ccr.ccs.tencentyun.com/o-pq/domu:latest
    expose:
      - "8080"
    volumes:
      - ./data:/app/data
    environment:
      - DATA_DIR=/app/data
      - JWT_SECRET=${JWT_SECRET}
      - BASE_URL=${BASE_URL:-https://domu.o-pq.com}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # Router
      - "traefik.http.routers.domu.rule=Host(`domu.o-pq.com`)"
      - "traefik.http.routers.domu.entrypoints=websecure"
      - "traefik.http.routers.domu.tls.certresolver=letsencrypt"
      # Service
      - "traefik.http.services.domu.loadbalancer.server.port=8080"
      - "traefik.http.services.domu.loadbalancer.healthcheck.path=/api/v1/health"
      - "traefik.http.services.domu.loadbalancer.healthcheck.interval=10s"
    networks:
        - traefik
networks:
  traefik:
    external: true
